sudo: required
before_install:
  - sudo apt-get install build-essential
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:
  - source install.sh

# Build steps
script:
  - mkdir build
  - cd build
  - ${DEPS_DIR}/cmake/bin/cmake .. && make
  - ./example 1000 100 1 12
