sudo: required
before_install:
  - sudo apt-get install build-essential
  - pip install --user pyyaml cpp-coveralls
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:
  - source install.sh

# Build steps
script:
  - cd test
  - ../deps/cmake/bin/cmake . && make
  - ./test_HODLR 1000 100 1 12
  - coveralls
