sudo: required
before_install:
  - sudo apt-get install build-essential
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  
  # Getting CMake:
  - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
  - mkdir cmake && wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

  # Getting Eigen:
  - wget http://bitbucket.org/eigen/eigen/get/3.3.5.tar.bz2"
  - tar xjf 3.3.5.tar.bz2
  - mv eigen-eigen-b3f3d4950030 eigen
  - export EIGEN_PATH=$PWD/eigen/
  # Go to the Root directory  
  - cd ..

# Build steps
script:
  - mkdir build
  - cd build
  - ${DEPS_DIR}/cmake/bin/cmake .. && make
  - ./example 16000 100 1
